[package]
name = "better_assertions_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
better_assertions = {path = "../", version = "0.1.1", features = ["debug_max_level_slow", "store_level_instant"]}

